podTemplate(containers: [
    containerTemplate(name: 'maven', image: 'artifacts.mlbinfra.net/docker/testengr/jenkins-jnlp-worker-mvn:v0.0.10', ttyEnabled: true, command: 'cat')
  ]) {
    node(POD_LABEL) {
      timestamps {
        container('maven') {
          stage('Install Dependencies') {
            checkout scm

              sh '''
                # Installs nodejs
                wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
                curl -sL https://deb.nodesource.com/setup_17.x | bash -
                apt-get update
                apt-get install -y nodejs
                
                node -v
                mvn -version
                java -version
              '''
            
          }

          stage ('Test'){
            sauce('tevs-sauce-on-demand'){
              sauceconnect(options: '--no-remove-colliding-tunnels --no-ssl-bump-domains *.qa-gcp.mlb.com --tunnel-domains qa-gcp.mlb.com --tunnel-cert public', useGeneratedTunnelIdentifier: true, verboseLogging: true) {
                sh "java -version"
                sh "mvn -version"
              }// end sauceconnect          
            }// end sauce
          }// end stage Test
        } // end container
      }//end timestamps
    }
}